name: Create Ultimate GFW Merged List

on:
  schedule:
    - cron: '0 8 * * *' # 每天北京时间下午4点运行 (UTC 8点)
  workflow_dispatch:

env:
  # 输出文件配置
  FILENAME: "GFW-Merged.list" # 新的合并文件名
  OUTPUT_DIR: "./Clash/Ruleset"

  # 规则源 URL
  SOURCE_URL_GFWLIST: "https://raw.githubusercontent.com/gfwlist/gfwlist/master/list.txt"
  SOURCE_URL_ACL4SSR: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

  # --- 复用你原来的文件头信息，并更新描述 ---
  DESCRIPTION: "# 终极 GFW 规则合并流程"
  ILLUSTRATE: "# 该规则集由 GFWList 和 ACL4SSR 合并而来，强强联合，确保覆盖面"
  RULES_SOURCE_HEADER: "# 基于以下源项目合并："
  AUTHOR: "# 作者：Reid_Vin_Action"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download, process, merge, and generate ruleset
        run: |
          # 确保脚本在任何命令失败时立即退出
          set -e

          # --- 步骤 1: 下载并转换 GFWList (复用之前的逻辑) ---
          echo "Processing source 1: GFWList..."
          curl -sL "${{ env.SOURCE_URL_GFWLIST }}" -o gfwlist_raw.txt
          
          cat gfwlist_raw.txt | \
          grep -vE '^!|^\[|^@@|^\s*$' | \
          sed -E 's#^\|\|##; s#^\|https?://##; s#^https?://##; s#^\.##' | \
          sed -E '/\*/d' | \
          sed -E 's|/.*||' | \
          sed '/^$/d' \
          > gfwlist_cleaned.tmp
          
          echo "GFWList processed. Found $(wc -l < gfwlist_cleaned.tmp) potential rules."

          # --- 步骤 2: 下载并清理 ACL4SSR 列表 ---
          echo "Processing source 2: ACL4SSR..."
          curl -sL "${{ env.SOURCE_URL_ACL4SSR }}" -o acl4ssr_raw.txt
          
          # ACL4SSR 已经是 Clash 格式，但我们只取域名部分，并移除注释和空行
          # paylod: 这部分我们不需要，只取DOMAIN开头的
          grep -E '^DOMAIN' acl4ssr_raw.txt > acl4ssr_cleaned.tmp

          echo "ACL4SSR processed. Found $(wc -l < acl4ssr_cleaned.tmp) rules."

          # --- 步骤 3: 合并、格式化并去重 ---
          echo "Merging, formatting and deduplicating..."

          # 将 gfwlist 的裸域名和 acl4ssr 的 clash 规则合并
          # 注意：gfwlist 的处理结果是不带 "DOMAIN-SUFFIX," 前缀的裸域名
          # acl4ssr 的处理结果是带 "DOMAIN-..." 前缀的完整规则
          # 我们将 gfwlist 的裸域名也加上 DOMAIN-SUFFIX 前缀再合并
          
          # 合并两个列表，然后排序去重
          {
            sed 's/^/DOMAIN-SUFFIX,/' < gfwlist_cleaned.tmp
            cat acl4ssr_cleaned.tmp
          } | sort -u > final_rules.txt

          RULES_COUNT=$(wc -l < final_rules.txt)
          echo "Merge complete. Total unique rules: $RULES_COUNT"
          
          # --- 准备文件头和元数据 ---
          UPDATE_TIME=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")
          
          # --- 生成最终文件 ---
          echo "Generating final output file..."
          mkdir -p ${{ env.OUTPUT_DIR }}
          FINAL_FILE_PATH="${{ env.OUTPUT_DIR }}/${{ env.FILENAME }}"
          
          {
            echo "${{ env.ILLUSTRATE }}"
            echo "${{ env.DESCRIPTION }}"
            echo "${{ env.RULES_SOURCE_HEADER }}"
            echo "# 1. GFWList: ${{ env.SOURCE_URL_GFWLIST }}"
            echo "# 2. ACL4SSR: ${{ env.SOURCE_URL_ACL4SSR }}"
            echo "# 更新时间：$UPDATE_TIME"
            echo "# 规则总数：${RULES_COUNT}条"
            echo "${{ env.AUTHOR }}"
            cat final_rules.txt
          } > "$FINAL_FILE_PATH"

          # --- 清理临时文件 ---
          rm gfwlist_raw.txt gfwlist_cleaned.tmp acl4ssr_raw.txt acl4ssr_cleaned.tmp final_rules.txt
          echo "Process complete! Final file is at $FINAL_FILE_PATH"

      - name: Push changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Reid_Vin
          author_email: reid_vin@outlook.com
          message: "feat: Create merged GFW ruleset from GFWList and ACL4SSR"
          add: "${{ env.OUTPUT_DIR }}/${{ env.FILENAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.COMMON_TOKEN }}
