name: Convert GFWList to Clash Rules

on:
  schedule:
    - cron: '0 8 * * *' # 每天北京时间下午4点运行 (UTC 8点)
  workflow_dispatch:

env:
  # 输出文件配置
  FILENAME: "GFWList.list"
  OUTPUT_DIR: "./Clash/Ruleset"

  # 规则源 URL (已更新为 gfwlist 的未编码版本)
  SOURCE_URL: "https://raw.githubusercontent.com/gfwlist/gfwlist/master/list.txt"

  # --- 复用你原来的文件头信息，并做微调 ---
  DESCRIPTION: "# GFWList 转换流程"
  ILLUSTRATE: "# 该规则集由 gfwlist 转换而来，并适配 Clash 使用"
  RULES_SOURCE_HEADER: "# 基于以下源项目转换："
  AUTHOR: "# 作者：Reid_Vin_Action"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download, convert, and generate ruleset
        run: |
          # 确保脚本在任何命令失败时立即退出
          set -e

          echo "Downloading GFWList source from ${{ env.SOURCE_URL }}..."
          curl -sL "${{ env.SOURCE_URL }}" -o gfwlist_raw.txt

          echo "Processing and converting rules..."
          # 核心转换步骤：
          # 1. grep -vE: 过滤掉以下行：
          #    - ^!        (注释)
          #    - ^\[       ([AutoProxy] 头部)
          #    - ^@@       (白名单规则)
          #    - ^\s*$     (空行)
          # 2. sed -E: 使用扩展正则表达式进行替换
          #    - s#^\|\|##: 移除行首的 ||
          #    - s#^\|https?://##: 移除行首的 |http:// 或 |https://
          #    - s#^https?://##: 移除行首的 http:// 或 https://
          #    - s#^\.##: 移除行首的 . (处理 .google.com 这类规则)
          # 3. sed -E '/\*/d': 删除所有包含通配符 '*' 的行，因为它们难以直接转换为Clash规则
          # 4. sed -E 's|/.*||': 删除域名后可能存在的路径部分 (例如 www.google.com/search?q=...)
          # 5. sed '/^$/d': 删除处理后可能产生的空行
          # 6. sed 's/^/DOMAIN-SUFFIX,/' : 为每一行添加 DOMAIN-SUFFIX, 前缀
          # 7. sort -u: 排序并去除重复项
          cat gfwlist_raw.txt | \
          grep -vE '^!|^\[|^@@|^\s*$' | \
          sed -E 's#^\|\|##; s#^\|https?://##; s#^https?://##; s#^\.##' | \
          sed -E '/\*/d' | \
          sed -E 's|/.*||' | \
          sed '/^$/d' | \
          sed 's/^/DOMAIN-SUFFIX,/' | \
          sort -u > converted_rules.txt
          
          RULES_COUNT=$(wc -l < converted_rules.txt)
          echo "Conversion complete. Total rules generated: $RULES_COUNT"
          
          # --- 准备文件头和元数据 ---
          UPDATE_TIME=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")
          
          # --- 生成最终文件 ---
          echo "Generating final output file..."
          mkdir -p ${{ env.OUTPUT_DIR }}
          FINAL_FILE_PATH="${{ env.OUTPUT_DIR }}/${{ env.FILENAME }}"
          
          {
            echo "${{ env.ILLUSTRATE }}"
            echo "${{ env.DESCRIPTION }}"
            echo "${{ env.RULES_SOURCE_HEADER }}"
            echo "# ${{ env.SOURCE_URL }}"
            echo "# 更新时间：$UPDATE_TIME"
            echo "# 规则总数：${RULES_COUNT}条"
            echo "${{ env.AUTHOR }}"
            cat converted_rules.txt
          } > "$FINAL_FILE_PATH"

          # --- 清理临时文件 ---
          rm gfwlist_raw.txt converted_rules.txt
          echo "Process complete! Final file is at $FINAL_FILE_PATH"

      - name: Push changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Reid_Vin
          author_email: reid_vin@outlook.com
          message: "feat: Auto update GFWList and convert to Clash rules"
          add: "${{ env.OUTPUT_DIR }}/${{ env.FILENAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.COMMON_TOKEN }}
