name: get-All-Diversion-Urls

on:
  schedule:
    - cron: '0 1 * * 0' # 每周日凌晨1点钟执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Scrape webpage and generate data
        run: python ./Scripts/Filter_All_Url.py

      - uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Reid_Vin
          author_email: reid_vin@outlook.com
          message: Automatic diversion rules update
          add: |
            "./Urls/All_Urls.list"
            "./Urls/All_Urls_No_Name.list"
        env:
          GITHUB_TOKEN: ${{ secrets.COMMON_TOKEN }}
