name: get-All-Diversion-Urls

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run Python script
        run: python Scripts/get_urls.py
        env:
          GITHUB_TOKEN: ${{ secrets.COMMON_TOKEN }}
          OUTPUT_FILE: ${{ github.workspace }}/Urls/All_Urls.list

      - name: Copy file to destination
        run: cp ${{ github.workspace }}/Urls/All_Urls.list ${{ github.workspace }}/Clash/Ruleset/All_Urls.list

      - name: Push changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Reid_Vin
          author_email: reid_vin@outlook.com
          message: Automatic diversion rules update
          add: "./Clash/Ruleset/All_Urls.list"
        env:
          GITHUB_TOKEN: ${{ secrets.COMMON_TOKEN }}
