name: Merge International Games List

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  # 生成的分流规则文件名
  FILENAME: "InternationalGames"
  # 分流规则描述
  DESCRIPTION: "# 国际游戏分流规则合集"
  # 需要合并的分流规则：
  DIVERSION_RULES_LIST_URLS: |
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Purikonejp/Purikonejp.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OP/OP.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gog/Gog.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Garena/Garena.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Supercell/Supercell.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WildRift/WildRift.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PlayStation/PlayStation.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Rockstar/Rockstar.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Overwatch/Overwatch.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HeroesoftheStorm/HeroesoftheStorm.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hearthstone/Hearthstone.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DiabloIII/DiabloIII.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Classic/Classic.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Battle/Battle.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xbox/Xbox.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Riot/Riot.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Nikke/Nikke.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/2KGames/2KGames.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Ubisoft/Ubisoft.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Roblox/Roblox.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NGA/NGA.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Assassin'sCreed-Odyssey/Assassin'sCreed-Odyssey.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Assassin'sCreed-Origins/Assassin'sCreed-Origins.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Majsoul/Majsoul.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Origin/Origin.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WorldofWarcraft/WorldofWarcraft.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/StarCraftII/StarCraftII.list
  ILLUSTRATE: "# 分流规则基于ios_rule_script大佬的规则合并而来，感谢大佬和其他贡献者的无私奉献"
  RULES_SOURCE: "# 基于以下分流规则合并："
  AUTHOR: "# 作者：Reid_Vin_Action"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download and process diversion rules
        run: |
          merged_rules=""
          rules_count=0
          temp_url=""
          for url in $DIVERSION_RULES_LIST_URLS; do
            if [ -z "$temp_url" ]; then
              temp_url="# $url"
            else
              temp_url="$temp_url"$'\n'"# $url"
            fi
            echo "Downloading diversion rules from $url..."
            curl -s $url -o list.txt

            echo "Processing diversion rules..."
            rules=$(grep -v '^#' list.txt)
            merged_rules="$merged_rules"$'\n'"$rules"
            current_rules_count=$(grep -c '^[^#[:space:]]' list.txt)
            rules_count=$((rules_count + current_rules_count))

            rm list.txt
          done

          update_time=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")
          echo "$ILLUSTRATE" > "./Clash/Ruleset/$FILENAME.list"
          echo "$DESCRIPTION" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$RULES_SOURCE" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$temp_url" >> "./Clash/Ruleset/$FILENAME.list"
          echo "# 更新时间：$update_time" >> "./Clash/Ruleset/$FILENAME.list"
          echo "# 规则总数：$rules_count条" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$AUTHOR" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$merged_rules" >> "./Clash/Ruleset/$FILENAME.list"

          echo "合并完成》》》"
      - name: Push changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Reid_Vin
          author_email: reid_vin@outlook.com
          message: Automatic diversion rules update
          add: "./Clash/Ruleset/${{ env.FILENAME }}.list"
        env:
          GITHUB_TOKEN: ${{ secrets.COMMON_TOKEN }}
