name: Merge iOS-CDN List

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

env:
  # 苹果服务的分流规则文件名
  FILENAME: "iOS_CDN"
  # 分流规则描述
  DESCRIPTION: "# 国内游戏分流规则合集"
  # 需要合并的分流规则：
  DIVERSION_RULES_LIST_URLS: |
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppStore/AppStore.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iCloud/iCloud.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TestFlight/TestFlight.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/FitnessPlus/FitnessPlus.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMail/AppleMail.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMusic/AppleMusic.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleNews/AppleNews.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Siri/Siri.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/FindMy/FindMy.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleProxy/AppleProxy.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iCloudPrivateRelay/iCloudPrivateRelay.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleDev/AppleDev.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleFirmware/AppleFirmware.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleHardware/AppleHardware.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMedia/AppleMedia.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Beats/Beats.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleID/AppleID.list
  ILLUSTRATE: "# 分流规则基于ios_rule_script大佬的规则合并而来，感谢大佬和其他贡献者的无私奉献"
  RULES_SOURCE: "# 基于以下分流规则合并："
  AUTHOR: "# 作者：Reid_Vin_Action"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download and process diversion rules
        run: |
          merged_rules=""
          rules_count=0
          temp_url=""
          for url in $DIVERSION_RULES_LIST_URLS; do
            if [ -z "$temp_url" ]; then
              temp_url="# $url"
            else
              temp_url="$temp_url"$'\n'"# $url"
            fi
            echo "Downloading diversion rules from $url..."
            curl -s $url -o list.txt

            echo "Processing diversion rules..."
            rules=$(grep -v '^#' list.txt)
            merged_rules="$merged_rules"$'\n'"$rules"
            current_rules_count=$(grep -c '^[^#[:space:]]' list.txt)
            rules_count=$((rules_count + current_rules_count))

            rm list.txt
          done

          update_time=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")
          echo "$ILLUSTRATE" > "./Clash/Ruleset/$FILENAME.list"
          echo "$DESCRIPTION" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$RULES_SOURCE" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$temp_url" >> "./Clash/Ruleset/$FILENAME.list"
          echo "# 更新时间：$update_time" >> "./Clash/Ruleset/$FILENAME.list"
          echo "# 规则总数：$rules_count条" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$AUTHOR" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$merged_rules" >> "./Clash/Ruleset/$FILENAME.list"

          echo "合并完成》》》"
      - name: Push changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Reid_Vin
          author_email: reid_vin@outlook.com
          message: Automatic diversion rules update
          add: "./Clash/Ruleset/${{ env.FILENAME }}.list"
        env:
          GITHUB_TOKEN: ${{ secrets.COMMON_TOKEN }}
