name: Merge ChinaMedia List

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

env:
  FILENAME: "CNMedia"
  DESCRIPTION: "# 国内媒体分流规则合并流程"
  DIVERSION_RULES_LIST_URLS: |
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Youku/Youku.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TencentVideo/TencentVideo.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iQIYI/iQIYI.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Douyu/Douyu.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Himalaya/Himalaya.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Himalaya/Himalaya.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BaoFengYingYin/BaoFengYingYin.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AcFun/AcFun.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/6JianFang/6JianFang.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Ku6/Ku6.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/KuaiShou/KuaiShou.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LeTV/LeTV.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Migu/Migu.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PPTV/PPTV.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YiZhiBo/YiZhiBo.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.list
  ILLUSTRATE: "# 分流规则基于ios_rule_script大佬的规则合并而来，感谢大佬和其他贡献者的无私奉献"
  RULES_SOURCE: "# 基于以下分流规则合并："
  AUTHOR: "# 作者：Reid_Vin_Action"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download and process diversion rules
        run: |
          merged_rules=""
          rules_count=0
          temp_url=""
          for url in $DIVERSION_RULES_LIST_URLS; do
            if [ -z "$temp_url" ]; then
              temp_url="# $url"
            else
              temp_url="$temp_url"$'\n'"# $url"
            fi
            echo "Downloading diversion rules from $url..."
            curl -s $url -o list.txt

            echo "Processing diversion rules..."
            rules=$(grep -v '^#' list.txt)
            merged_rules="$merged_rules"$'\n'"$rules"
            current_rules_count=$(grep -c '^[^#[:space:]]' list.txt)
            rules_count=$((rules_count + current_rules_count))

            rm list.txt
          done

          update_time=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")
          echo "$ILLUSTRATE" > "./Clash/Ruleset/$FILENAME.list"
          echo "$DESCRIPTION" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$RULES_SOURCE" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$temp_url" >> "./Clash/Ruleset/$FILENAME.list"
          echo "# 更新时间：$update_time" >> "./Clash/Ruleset/$FILENAME.list"
          echo "# 规则总数：$rules_count条" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$AUTHOR" >> "./Clash/Ruleset/$FILENAME.list"
          echo "$merged_rules" >> "./Clash/Ruleset/$FILENAME.list"

          echo "合并完成》》》"
      - name: Push changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Reid_Vin
          author_email: reid_vin@outlook.com
          message: Automatic diversion rules update
          add: "./Clash/Ruleset/${{ env.FILENAME }}.list"
        env:
          GITHUB_TOKEN: ${{ secrets.COMMON_TOKEN }}
