name: Test Environment Variables

on:
  workflow_dispatch:

env:
  DIVERSION_RULES_LIST_URLS: |
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HoYoverse/HoYoverse.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/TencentLoLMobile/TencentLoLMobile.list
  ILLUSTRATE: 分流规则基于ios_rule_script大佬的规则合并而来，感谢大佬和其他贡献者的无私奉献
  FILENAME: ChinaGame

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "DIVERSION_RULES_LIST_URLS:"
          echo "$DIVERSION_RULES_LIST_URLS"
          echo "ILLUSTRATE:"
          echo "$ILLUSTRATE"
          echo "FILENAME:"
          echo "$FILENAME"

          # 将上游分流 URL 字符串分割成数组
          IFS=$'\n' read -d '' -r -a URLS <<< "$DIVERSION_RULES_LIST_URLS"
          # 打印数组内容以进行验证
          echo "URLS array:"
          printf '%s\n' "${URLS[@]}"

          # 初始化一个空字符串来存储合并的规则
          merged_rules=""

          # 遍历 URL 数组
          for url in "${URLS[@]}"; do
            echo "Downloading diversion rules from $url..."
            curl -s $url -o list.txt

            echo "Processing diversion rules..."
            rules=$(grep -v '^#' list.txt)
            merged_rules+="$rules\n"

            rm list.txt
          done

          # 打印合并的规则以进行验证
          echo "Merged rules:"
          echo "$merged_rules"

          # 将解释说明和合并的规则写入最终的文件
          echo -e "$ILLUSTRATE\n$merged_rules" > ./Clash/Ruleset/$FILENAME.list

          echo "合并完成"
