name: Test Environment Variables

on:
  workflow_dispatch:

env:
  DIVERSION_RULES_LIST_URLS: |
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HoYoverse/HoYoverse.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/TencentLoLMobile/TencentLoLMobile.list
  ILLUSTRATE: 分流规则基于ios_rule_script大佬的规则合并而来，感谢大佬和其他贡献者的无私奉献
  FILENAME: ChinaGame

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "DIVERSION_RULES_LIST_URLS:"
          echo "$DIVERSION_RULES_LIST_URLS"
          echo "ILLUSTRATE:"
          echo "$ILLUSTRATE"
          echo "FILENAME:"
          echo "$FILENAME"

          # 在脚本中使用循环处理每个 URL 地址
          echo "Downloading and processing URLs..."
          for url in $DIVERSION_RULES_LIST_URLS; do
            echo "Downloading diversion rules from $url..."
            curl -s "$url" -o list.txt
            echo "Processing diversion rules..."
            rules=$(grep -v '^#' list.txt)
            echo "$rules" >> merged_rules.txt
            rm list.txt
          done

          echo "合并完成》》》"
