name: Update

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  DIVERSION_RULES_LIST_URLS: |
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HoYoverse/HoYoverse.list
    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/TencentLoLMobile/TencentLoLMobile.list
  ILLUSTRATE: "分流规则基于ios_rule_script大佬的规则合并而来，感谢大佬和其他贡献者的无私奉献"
  FILENAME: "ChinaGame"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and process diversion rules
        run: |
          merged_rules=""
          for url in $DIVERSION_RULES_LIST_URLS; do
            echo "Downloading diversion rules from $url..."
            curl -s $url -o list.txt

            echo "Processing diversion rules..."
            rules=$(grep -v '^#' list.txt)
            merged_rules="$merged_rules"$'\n'"$rules"

            rm list.txt
          done

          printf "%s\n%s\n" "$ILLUSTRATE" "$merged_rules" > "./Clash/Ruleset/${{ env.FILENAME }}.list"

          echo "合并完成》》》"
      - name: Push changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: YourNameHere
          author_email: your.email@example.com
          message: Automatic diversion rules update
          add: "./Clash/Ruleset/${{ env.FILENAME }}.list"
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
